module.exports = {
	plugins: ["prettier-plugin-tailwindcss"],
	importOrderSortSpecifiers: true,
	importOrderGroupNamespaceSpecifiers: true,
	importOrderCaseInsensitive: false,
	importOrderSeparation: false,
	printWidth: 80,
	tabWidth: 4,
	useTabs: true,
	semi: true,
	singleQuote: false,
	jsxSingleQuote: false,
	trailingComma: "all",
	bracketSpacing: true,
	bracketSameLine: false,
	arrowParens: "always",
	htmlWhitespaceSensitivity: "strict",
	endOfLine: "lf",
};